---
- name: Create the OpenStack resources for cluster installation
  hosts: localhost
  tasks:
  - name: provision cluster
    include_role:
      name: openshift_openstack
      tasks_from: provision.yml


# NOTE(shadower): Bring in the host groups:
- name: evaluate groups
  import_playbook: ../../init/evaluate_groups.yml


- name: Wait for the nodes and gather their facts
  hosts: oo_all_hosts
  become: yes
  # NOTE: The nodes may not be up yet, don't gather facts here.
  # They'll be collected after `wait_for_connection`.
  gather_facts: no
  tasks:
  - name: Wait for the the nodes to come up
    wait_for_connection:

  - name: Gather facts for the new nodes
    setup:

- name: set common facts
  import_playbook: ../../init/facts.yml


# TODO(shadower): consider splitting this up so people can stop here
# and configure their DNS if they have to.
- name: Populate the DNS entries
  hosts: localhost
  tasks:
  - name: Populate DNS entries
    include_role:
      name: openshift_openstack
      tasks_from: populate-dns.yml
    when:
    - openshift_openstack_external_nsupdate_keys is defined
    - openshift_openstack_external_nsupdate_keys.private is defined or openshift_openstack_external_nsupdate_keys.public is defined

- name: Configure Subscriptions and Package Repositories
  hosts: oo_all_hosts
  become: yes
  gather_facts: yes
  tasks:
  - name: Subscribe RHEL instances
    include_role:
      name: rhel_subscribe
    when:
    - ansible_distribution == "RedHat"
    - rhsub_user is defined
    - rhsub_pass is defined

  - name: Enable required YUM repositories
    include_role:
      name: openshift_repos

- name: Configure os_firewall
  hosts: oo_masters_to_config:oo_etcd_to_config:oo_lb_to_config:oo_nfs_to_config:oo_nodes_to_config
  roles:
  - role: os_firewall

- name: Prepare the Nodes in the cluster for installation
  hosts: oo_all_hosts
  become: yes
  gather_facts: yes
  tasks:      
  - name: Install dependencies
    include_role:
      name: openshift_openstack
      tasks_from: node-packages.yml

  - name: Configure Node
    include_role:
      name: openshift_openstack
      tasks_from: node-configuration.yml
